# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.4

# Mod Properties
mod_version=1.1.12
maven_group=moe.zapic
archives_base_name=clock-hud

# Dependencies
fabric_version=0.140.2+1.21.11
cloth_config_version=21.11.153
mod_menu_version=17.0.0-beta.1
